# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - osteoscreen

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://osteoscreen.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_d0e797b5f7844ddca682a2ea830e94b9 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_8a8b9a86cb8f47888b3751ed2a5a3ee2 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: osteoscreen.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_d0e797b5f7844ddca682a2ea830e94b9 }}/osteoscreen:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'osteoscreen'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_69fa2a6342f74517a4360e13553e47ac }}
        images: 'osteoscreen.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_d0e797b5f7844ddca682a2ea830e94b9 }}/osteoscreen:${{ github.sha }}'